[profile.default]
solc_version = "0.8.17"
evm_version = "shanghai"
src = 'src'
out = 'out'
libs = ['lib']

[profile.fuzz]
max_test_rejects = 100000

# See more config options https://github.com/foundry-rs/foundry/tree/master/config